export const FETCH_TACTIC = 'FETCH_TACTIC';
export const FETCH_TACTIC_PENDING = 'FETCH_TACTIC_PENDING';
export const FETCH_TACTIC_FULFILLED = 'FETCH_TACTIC_FULFILLED';
export const FETCH_TACTIC_REJECTED = 'FETCH_TACTIC_REJECTED';
