export const FETCH_TACTICS_REQUEST = 'FETCH_TACTICS_REQUEST';
export const FETCH_TACTICS_SUCCESS = 'FETCH_TACTICS_SUCCESS';
export const FETCH_TACTICS_FAILURE = 'FETCH_TACTICS_FAILURE';

export const SELECT_TACTIC = 'SELECT_TACTIC';

export const OPEN_NEW_TACTIC_DIALOG = 'OPEN_NEW_TACTIC_DIALOG';
export const CLOSE_NEW_TACTIC_DIALOG = 'CLOSE_NEW_TACTIC_DIALOG';
