export const GLOBAL_ERROR = 'GLOBAL_ERROR';

export const FETCH_TACTIC = 'FETCH_TACTIC';
export const FETCH_TACTIC_PENDING = 'FETCH_TACTIC_PENDING';
export const FETCH_TACTIC_FULFILLED = 'FETCH_TACTIC_FULFILLED';
export const FETCH_TACTIC_REJECTED = 'FETCH_TACTIC_REJECTED';

export const FETCH_TACTICS = 'FETCH_TACTICS';
export const FETCH_TACTICS_PENDING = 'FETCH_TACTICS_PENDING';
export const FETCH_TACTICS_FULFILLED = 'FETCH_TACTICS_FULFILLED';
export const FETCH_TACTICS_REJECTED = 'FETCH_TACTICS_REJECTED';

export const CREATE_TACTIC = 'CREATE_TACTIC';
export const CREATE_TACTIC_PENDING = 'CREATE_TACTIC_PENDING';
export const CREATE_TACTIC_FULFILLED = 'CREATE_TACTIC_FULFILLED';
export const CREATE_TACTIC_REJECTED = 'CREATE_TACTIC_REJECTED';

export const OPEN_CREATE_TACTIC_DIALOG = 'OPEN_CREATE_TACTIC_DIALOG';
export const CLOSE_CREATE_TACTIC_DIALOG = 'CLOSE_CREATE_TACTIC_DIALOG';

export const SELECT_TACTIC = 'SELECT_TACTIC';