export const FETCH_TACTICS = 'FETCH_TACTICS';
export const FETCH_TACTICS_PENDING = 'FETCH_TACTICS_PENDING';
export const FETCH_TACTICS_FULFILLED = 'FETCH_TACTICS_FULFILLED';
export const FETCH_TACTICS_REJECTED = 'FETCH_TACTICS_REJECTED';

export const CREATE_TACTIC = 'CREATE_TACTIC';
export const CREATE_TACTIC_REQUEST = 'CREATE_TACTIC_REQUEST';
export const CREATE_TACTIC_SUCCESS = 'CREATE_TACTIC_SUCCESS';
export const CREATE_TACTIC_FAILURE = 'CREATE_TACTIC_FAILURE';

export const OPEN_NEW_TACTIC_DIALOG = 'OPEN_NEW_TACTIC_DIALOG';
export const CLOSE_NEW_TACTIC_DIALOG = 'CLOSE_NEW_TACTIC_DIALOG';

export const SELECT_TACTIC = 'SELECT_TACTIC';